name: Moxfield User Stats Test

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-22.04
    # TODO: Set up services for database & more once we transform to webapp
    #    services:
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.10.14
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.14
          cache: 'pip'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test Moxfield User Stats
        run: python main.py --username=mainframe

